name: padis-mri
channels:
  - pytorch
  - nvidia
  - astra-toolbox/label/dev
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.6.0=h6a678d5_0
  - astra-toolbox=2.2.0=py39h4319877_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - binutils_impl_linux-64=2.40=h5293946_0
  - blas=1.1=openblas
  - blosc=1.21.3=h6a678d5_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py39h6a678d5_8
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.7.15=h06a4308_0
  - certifi=2025.8.3=py39h06a4308_0
  - cffi=1.17.1=py39h15c3d72_0
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py39h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.2.0=py39hdb19cb5_0
  - cryptography=45.0.5=py39hea9ce0a_0
  - cuda-cudart=11.8.89=0
  - cuda-version=11.8=hcce14f8_3
  - cudatoolkit=11.8.0=h6a678d5_0
  - cudnn=8.9.7.29=hbc23b4c_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py39hf88036b_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.3=h6a678d5_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py39h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - gcc=14.2.0=h96c4ede_1
  - gcc_impl_linux-64=14.2.0=h6b349bd_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py39h06a4308_0
  - imagecodecs=2023.1.23=py39hc4b7b5f_0
  - imageio=2.33.1=py39h06a4308_0
  - importlib-metadata=8.5.0=pyha770c72_1
  - importlib_resources=6.4.0=py39h06a4308_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jmespath=1.0.1=py39h06a4308_0
  - joblib=1.4.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jxrlib=1.1=h7b6447c_2
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lazy_loader=0.4=py39h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libastra=2.2.0=cuda_11.8_0
  - libavif=0.11.1=h5eee18b_0
  - libblas=3.9.0=26_linux64_openblas
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcblas=3.9.0=26_linux64_openblas
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcufft=10.9.0.58=0
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.9.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=14.2.0=h41c2201_101
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - liblapack=3.9.0=26_linux64_openblas
  - liblapacke=3.9.0=26_linux64_openblas
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libpng=1.6.43=h2797004_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=3.21.12=hfc55251_2
  - libsanitizer=14.2.0=h2a3dede_1
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - libzlib=1.2.13=h4ab18f5_6
  - libzopfli=1.0.3=he6710b0_0
  - lz4-c=1.9.4=h6a678d5_1
  - magma=2.5.4=hc72dce7_4
  - make=4.4.1=hb9d3cd8_2
  - matplotlib=3.9.2=py39h06a4308_0
  - matplotlib-base=3.9.2=py39hbfdbfaf_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2022.1.0=hc2b9512_224
  - mkl-service=2.4.0=py39hb699420_0
  - mkl_fft=1.3.1=py39h051f8f4_4
  - mkl_random=1.2.2=py39h8b66066_1
  - mysql=5.7.24=h721c034_2
  - nccl=2.23.4.1=h03a54cd_3
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.2.1=py39h06a4308_0
  - ninja=1.12.1=h297d8ca_0
  - numpy=1.26.4=py39heeff2f4_0
  - numpy-base=1.26.4=py39h8a23956_0
  - openblas=0.3.28=pthreads_h6ec200e_1
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.4.0=h7b32b05_1
  - packaging=24.1=py39h06a4308_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.4.0=py39h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - ply=3.11=py39h06a4308_0
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyopenssl=25.1.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.20=he870216_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=cuda112py39hb0b7ed5_201
  - pytorch-mutex=1.0=cuda
  - pyzmq=26.2.0=py39h4e4fb57_1
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py39h06a4308_0
  - scikit-image=0.24.0=py39h1128e8f_0
  - scikit-learn=1.5.1=py39h1128e8f_0
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=75.1.0=py39h06a4308_0
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.7=h1b44611_2
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py39h2f386ee_0
  - tifffile=2023.4.12=py39h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py39h06a4308_0
  - torchvision=0.15.2=cuda118py39h196c800_0
  - tornado=6.4.1=py39h5eee18b_0
  - tqdm=4.66.5=py39h2f386ee_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=py39h06a4308_0
  - unicodedata2=15.1.0=py39h5eee18b_0
  - urllib3=1.26.19=py39h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h59595ed_1
  - zfp=1.0.0=h6a678d5_0
  - zipp=3.20.2=py39h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - annotated-types==0.7.0
      - awscli==1.42.21
      - boto3==1.40.21
      - botocore==1.40.21
      - cachetools==5.5.2
      - colorama==0.4.6
      - diffusers==0.31.0
      - docker-pycreds==0.4.0
      - docutils==0.19
      - eval-type-backport==0.2.2
      - filelock==3.16.1
      - fsspec==2024.10.0
      - future==1.0.0
      - geojson==3.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.3.1
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - h5py==3.12.1
      - huggingface-hub==0.26.2
      - imageio-ffmpeg==0.5.1
      - labelbox==7.2.0
      - lbox-clients==1.1.2
      - llvmlite==0.43.0
      - mripy==0.7.3
      - nibabel==5.3.2
      - numba==0.60.0
      - nvidia-htop==1.2.0
      - odl==0.7.0
      - pandas==2.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.0
      - pydantic-core==2.33.0
      - pyspng==0.1.2
      - pytz==2025.2
      - pywavelets==1.6.0
      - pyyaml==6.0.2
      - regex==2024.9.11
      - rsa==4.7.2
      - s3transfer==0.13.1
      - safetensors==0.4.5
      - sentry-sdk==2.24.1
      - setproctitle==1.3.5
      - sigpy==0.1.26
      - smmap==5.0.2
      - strenum==0.4.15
      - termcolor==3.1.0
      - typing-extensions==4.13.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - wandb==0.19.8
prefix: /home/rohan/miniconda3/envs/edm1
